# This is the folder where 
# the images will be downloaded to
downloadDestination: ""

# It preloads the pages on 
# the 2nd part of the script 
# for faster-showing prompts
# (Disable it if you have a really slow connection)
preloadPages: true

# Enable cache or not
#cache: true
# How often the cache gets renewed if found
# (Number is in days)
#cacheFrequency: 4